name: Lint Docs
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - docs-*

jobs:
  latex_indent:
    name: 🧽 Lint LaTeX
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: LaTeX linter (chktex)
      uses: j2kun/chktex-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
