name: Edit Mode Unit Tests
on:
  push:
    branches:
      - feat-*
      - fix-*
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Unit Testing
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: test/CampusConnectionsTest
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Code Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage results
          path: CodeCoverage/Report